CANNY_THRESHOLD: 66
FEATHER:
  X: 0.075
  Y: 0.075
HOUGHCIRCLES:
  THRESHOLD: 200
  PARAM1: 50
  PARAM2: 22
  MIN_RADIUS: 0
  MAX_RADIUS: 0
IMAGE:
  HEIGHT: 512
  WIDTH: 640
CRATE:
  ROWS: 4
  COLS: 5
TEMPLATE:
  IMAGE: assets/ok.png
  WIDTH: 100 # resizes template 100x100
  HEIGHT: 100
MATCHING:
  ERROR_THRESHOLD: 40 # 0-100 percentage

